spring:
    datasource:
        jdbc-url: jdbc:derby://localhost:1527/DAE
        driver-class-name: org.apache.derby.jdbc.ClientDriver
        username: dae
        password: dae
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            dialect: org.hibernate.dialect.DerbyTenSevenDialect