spring:
    datasource:
        jdbc-url: jdbc:derby://localhost:1527/DAE
        driver-class-name: org.apache.derby.jdbc.ClientDriver
        username: dae
        password: dae
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            dialect: org.hibernate.dialect.DerbyTenSevenDialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: adrianpelopez@gmail.com
        password: clkbmghpwjlvjemn
        properties:
            mail:
                auth: true
                starttls:
                    enable: true